### ISSUE TITLE
Add Active Patients

### ISSUE THREAD

**Issue by PRijnbeek** [darwin-eu-dev/CdmOnboarding#22]
In the questionnaire it say the active patients is calculated in the package but this is not done.

**Comment by MaximMoinat** [comment]
We need to define active patients. My suggestion:
- Take as 'index' date the `cdm_source. source_release_date` or current date if empty
- Look 6mo back and count unique persons with an overlapping observation period.

In pseudo-code:
```sql
select count(distinct person_id)
from observation_period
where observation_period_end_date >= (index_date - 6 months)
```

**Comment by MaximMoinat** [comment]
Or implement as a figure, similar to the Achilles "Persons With Continuous Observation By Month"
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/17825660/195095405-dfc15ffe-c31c-4e62-af65-01188794b78b.png">

**Comment by MaximMoinat** [comment]
Implemented both
